defaults:
  run:
    working-directory: geerlingguy.nfs
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out the codebase.
      uses: actions/checkout@v4
      with:
        path: geerlingguy.nfs
    - name: Set up Python 3.
      uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - name: Install Ansible.
      run: pip3 install ansible-core
    - name: Trigger a new import on Galaxy.
      run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo
        ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} |
        cut -d/ -f2)
name: Release
'on':
  push:
    tags:
    - '*'
